version: '3.4'

services:
  rabbitmq:
    ports:
      - 15672:15672
      - 5672:5672
    #volumes:
    #  - rabbitvolume:/var/lib/rabbitmq

  azurite:
    command: 'azurite-blob --blobHost 0.0.0.0 --blobPort 10000'
    ports:
      - 10000:10000
    #volumes:
    #  - azuritevolume:/data 
   
  mongo:
    ports:
      - 27017:27017
    volumes:
      - mongovolume:/data/db

  perfect.sagaservice.host:
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ConnectionStrings__RabbitMq=amqp://guest:guest@host.docker.internal:5672/
      - ConnectionStrings__Mongo=mongodb://host.docker.internal:27017/

  perfect.fileservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__BlobStorage=AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;DefaultEndpointsProtocol=http;BlobEndpoint=http://host.docker.internal:10000/devstoreaccount1;
      - ConnectionStrings__RabbitMq=amqp://guest:guest@host.docker.internal:5672/
    ports:
      - 7214:443
      - 5233:80
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  perfect.analyzerservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80      
      - ConnectionStrings__FileService=http://host.docker.internal:5233/
      - ConnectionStrings__RabbitMq=amqp://guest:guest@host.docker.internal:5672/
    ports:
      - 5062:80
      - 7095:443
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
