version: '3.4'

volumes:
  rabbitvolume:
  azuritevolume:
  mongovolume:

services:
  rabbitmq:
    image: masstransit/rabbitmq #rabbitmq:3-management
    container_name: 'some-rabbit'
    networks:
        - rabbitmq_go_net

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: 'some-azurite'
    networks:
        - azurite_go_net
   
  mongo:
    image: mongo
    container_name: 'some-mongo'
    networks:
        - mongo_go_net
        
  perfect.fileservice.api:
    image: ${DOCKER_REGISTRY-}perfectfileserviceapi
    container_name: 'perfect.fileservice.api'
    build:
      context: .
      dockerfile: Perfect.FileService.Api/Dockerfile
      
  perfect.analyzerservice.api:
    image: ${DOCKER_REGISTRY-}perfectanalyzerserviceapi
    container_name: 'perfect.analyzerservice.api'
    build:
      context: .
      dockerfile: Perfect.AnalyzerService.Api/Dockerfile
      
  perfect.sagaservice.host:
    image: ${DOCKER_REGISTRY-}perfectsagaservicehost
    container_name: 'perfect.sagaservice.host'
    build:
      context: .
      dockerfile: Perfect.SagaService.Host/Dockerfile

networks:
  rabbitmq_go_net:
    driver: bridge
  azurite_go_net:
    driver: bridge
  mongo_go_net:
    driver: bridge