version: '3.4'

services:
  rabbitmq:
    ports:
      - 15672:15672
      - 5672:5672
    #volumes:
    #  - rabbitvolume:/var/lib/rabbitmq

  azurite:
    command: 'azurite-blob --blobHost 0.0.0.0 --blobPort 10000'
    ports:
      - 10000:10000
    #volumes:
    #  - azuritevolume:/data 
   
  mongo:
    ports:
      - 27017:27017
    volumes:
      - mongovolume:/data/db

  perfect.sagaservice.host:
    environment:
      - DOTNET_ENVIRONMENT=Development

  perfect.fileservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - 7214:443
      - 5233:80
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  perfect.analyzerservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - 5062:80
      - 7095:443
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
